services:
#    bayard_newsletter_orm.example:
#        class: Bayard\NewsletterORMBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    newsletterorm.admanager:
        class: Bayard\Open4XMLParserBundle\Services\NewsManager
        arguments:
            $em : '@doctrine.orm.entity_manager'
            $version: 'latest'
            $region: '%aws_s3_region%'
            $key: '%aws_api_key%'
            $secret: '%aws_api_secret_key%'
            $bucket: '%aws_s3_generic_form_bucket%'
            $newslettersLocation: '%aws_s3_newsletter_location%'