<?php

namespace Bayard\NewsletterORMBundle\Repository;

use \Doctrine\ORM\EntityRepository;
/**
 * NewsletterTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsletterTypeRepository extends EntityRepository
{

}
